### ISSUE TITLE
Hello there 

### ISSUE THREAD

**Issue by EnderElohim** [Zilox135/InfernoRunner#1]
Hello there :D I just released me my friend's first pc game and here it is

https://moonlightstd.itch.io/hell-runner-ea

I hope it don't come up rude or anything but i wanted to just ask would you like to change your game's name please ^^ Both of our game names is Hell Runner and if you honour my request and change it if you don't mind that would be great. If not well i tried :D

**Comment by Zilox135** [comment]
Hello. In normal circumstances I would usually say no to something like this, but since this game was made only for a game jam I am willing to change the name so that you can have it for your game.

**Comment by EnderElohim** [comment]
Thank you very much and to be honest only reason I even dare to ask was because it was a game jam game and it being public on github ^^
Did you had change to check my game? It is two man team project and basically our firstborn baby 😃 I hope it can be a good game to kickstart our game company ^^
In mean time still waiting for itchio to make our game visible I think it take some time because we are new. Do you know anything we should do to make it faster? Currently only those with link can see our game. Thanks for your attention again much love.
https://moonlightstd.itch.io/hell-runner-ea

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Zilox135** [comment]
No worries. I did have some time to checkout your games page on itch.io and it is looking very nice, it looks like you have put a lot of work into it, so I am happy to change the name for you. As for the viability on itch.io I am not sure. I have only published one game on there so far, but I don't remember if it was visible straight away or not.

**Comment by Zilox135** [comment]
The project name was changed.
